### ISSUE TITLE
Port existing build tasks to Grunt

### ISSUE THREAD

**Issue by roblarsen** [roblarsen/CeeJS#20]
- Minify/package for download
- JSHint
- Watch task
- Run unit tests (Which aren't at all automated right now)
- Documentation. The documentation is already started as JSDoc. 
- Publish demos and documentation to gh-pages

**Comment by bobholt** [comment]
Are you working on this, or you want I should?

**Comment by roblarsen** [comment]
I was going to do it, as these shouldn't take all that long. Well, except for the pushing new stuff to the gh-pages branch, which I've never done. But if you want to- awesome. 

I'm also not sure what other new-fangled touches make sense. I don't want to make it a one way project (you must build with grunt or you must install it with bower type of thing) but I would like to be nice about those sort of things. 

I've had use to use this project again (the first time I've touched canvas in over a year) and... it remains useful! I figured I'd jumpstart it a little bit.

**Comment by bobholt** [comment]
Yeah, it shouldn't take too long. I tried a gh-pages plugin that didn't
work so well, but there's probably a better one out there.

I've learned a lot from @cowboy about cool ways to structure Grunt tasks,
so I'll take this on and apply my insider knowledge here.

**Comment by roblarsen** [comment]
Then sir, you and your insider @cowboy knowledge win the internets.

**Comment by bobholt** [comment]
Staus Report.

So far:
- Added JSCS and JSHint for static analysis and code style
- Found some bugs because of JSHint and fixed 'em
- Cleaned up code style a bit. That took a while.
- Got copy and minification done

Next:
- Watch
- Docs
- testing
- gh-pages

**Comment by roblarsen** [comment]
awesome \o/

**Comment by bobholt** [comment]
Updated Jasmine submodule to v2.1 in browser tests to match grunt task. Had to disable the imagediff tests - will open a ticket to fix those.

just gh-pages left... tomorrow.

**Comment by roblarsen** [comment]
Awesome stuff. The gh-pages is lower priority, so if it turns into weirdness, then that's that. I'm not even sure how that would work with authentication, etc. but it would be awesome to be able to make sure the documentation and samples (source files) are updated easily. I wonder if a separate workflow would be needed.

Let me know what you come up with. I'm really interested in how this piece works.

**Comment by bobholt** [comment]
re: authentication for gh-pages, it works seamlessly if you are using ssh, not https. I actually don't know how it works if you use https... hopefully it asks you for a password?
