### ISSUE TITLE
Implement Build Script

### ISSUE THREAD

**Issue by bobholt** [roblarsen/CeeJS#4]
One of the TODOs is BUILD SCRIPT

I can work on this, but what kind of tasks are we looking for other than minification of Canvas.js? 

I'd love to do auto-documentation, based on JSDoc or whatever.

**Comment by roblarsen** [comment]
Long term, I'm looking at maybe four things. 
1. Minify/package for download
2. JSHint?
3. Run unit tests (Which aren't at all automated right now)
4. Documentation.  The documentation is already started as JSDoc. Running it as an ant task is pretty easy.

1 and 4 are the minimum for now. The other two are optional.

**Comment by bobholt** [comment]
I'll set up a build for minification, jshint (easy to implement), and documentation. Unit tests and getting them in the build will take a little longer to get my head around.

**Comment by roblarsen** [comment]
Yeah, the unit testing is more long term. Marc has been looking at it, but it's the kind of thing that will just have to happen when it happens. In terms of doing it with Ant, it's actually not bad, it's setting up decent unit tests and specifically unit testing with Canvas elements, that's the issue.

**Comment by marcneuwirth** [comment]
Any preferences on unit testing frameworks?

**Comment by roblarsen** [comment]
I don't particularly care. I've done a lot with qunit, but that means zip, really. As long as it can be automated.

**Comment by bobholt** [comment]
So, as you can see, the build script is minifying the js file in the root directory and publishing the docs into /docs. I'm not currently changing the source in /index.html to point to the minified version, but I figured we wouldn't necessarily want to.

I noticed a couple of tidying-up issues I can take care of in the build script, but is there anything particularly outstanding that seems wanting?

**Comment by roblarsen** [comment]
TODO: set up a build task that pushes the new demos to the gh-pages branch (or otherwise figure out how to easily share the demos and the documentation on the gh-pages branch)

**Comment by roblarsen** [comment]
Functional for now. I'm going to move the project to some magical new build system.

Grunt, actually.  Which I guess isn't the hot sauce build system, but I'm not very trendy. 

New issues will be opened. It will be awesome.

**Comment by marcneuwirth** [comment]
:rocket:
