### ISSUE TITLE
Functions should implement parameters in the order in which they are given

### ISSUE THREAD

**Issue by marcneuwirth** [roblarsen/CeeJS#7]
For example in the circle function:

```
if (fillStyle) {
    context.fillStyle = fillStyle;
    context.fill();
}
if (strokeStyle) {
    context.strokeStyle = strokeStyle;
    stroke();
}
```

However:

```
canvas.fill();
canvas.stroke();
```

is different from:

```
canvas.stroke();
canvas.fill();
```

**Comment by roblarsen** [comment]
BACK from india. 

@marcneuwirth you're a fancy programmer. I see your point, but... what are you suggesting? What does this look like to an end user?

**Comment by marcneuwirth** [comment]
I have been thinking about a good way to do this in the back of my mind and this is what I have come up with, would love to hear ideas from you guys though.
- Basically namespace all of the attr setting functions inside of Canvas, though expose them at the top level to the outside.
- Add an additional param that will allow you to apply the corresponding action directly, ie set fillStyle and fill in one function call instead of two.
- Loop through all of the parameters passed into certain functions, if there is a corresponding function in the attributes namespace, call that function with the execute parameter

Something like this:

```
var Canvas = function() {

    var attr = {
        fillStyle: function(color, canFill) {
            console.log("fillStyle - " + color);
            if (canFill) {
                fill();
            }
        },
        strokeStyle: function(color, canStroke) {
            console.log("strokeStyle - " + color);
            if (canStroke) {
                stroke();
            }
        }
    },
    stroke = function() {
        console.log("Stroke");
    },
    fill = function() {
        console.log("Fill");
    }
    circle = function(params) {
        var x = params.x || 0,
            y = params.y || 0,
            radius = params.radius || 10;

        //make circle
        _executeParams(params);

    },
    _executeParams = function(params) {
        for (var param in params) {
            if (attr[param] !== undefined) {
                attr[param](params[param], true);
            }
        }
    };

    return {
        circle: circle,
        fill: fill,
        stroke: stroke,
        stokeStyle: attr.strokeStyle,
        fillStyle: attr.fillStyle
    }
}();


Canvas.circle({
    x: 25,
    y: 25,
    radius: 10,
    fillStyle: 'rgb(200,0,0)',
    strokeStyle: '#000000'
});​
```

http://jsfiddle.net/marcneuwirth/Gyspa/

**Comment by roblarsen** [comment]
Per our super secret chat, I think we'll just always just do it in this order: fill > stroke. We can revisit if people need to do something else. Done and dusted.
